# Generated by Django 5.2.7 on 2025-10-03 17:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mineral_or_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_registration', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit', models.CharField(default='tons', max_length=20)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.inventoryentry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
