# Generated by Django 5.2.7 on 2025-10-10 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryentry_analysis_results_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='truck_registration',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['deleted', 'date'], name='inventory_i_deleted_ef8e1a_idx'),
        ),
    ]
