# Generated by Django 5.2.7 on 2025-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
