# Generated by Django 5.2.7 on 2025-10-11 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inventory/attachments/%Y/%m/')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('spec', 'Spec'), ('other', 'Other')], default='photo', max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('size_kb', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventoryentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entry'], name='inventory_i_entry_i_954830_idx'), models.Index(fields=['checksum'], name='inventory_i_checksu_de502e_idx')],
            },
        ),
    ]
