# procurement/service.py
from __future__ import annotations

from django.conf import settings
from django.db import transaction
from django.utils import timezone

from .models import LPOSequence, LPO


def _next_year_counter() -> tuple[int, int]:
    """
    Returns (year, counter_after_increment) using a single global LPOSequence row per year.
    Safe under concurrency via select_for_update.
    """
    year = timezone.now().year
    with transaction.atomic():
        seq, _ = LPOSequence.objects.select_for_update().get_or_create(year=year)
        seq.counter += 1
        seq.save(update_fields=["counter"])
        return year, seq.counter


def next_lpo_number() -> str:
    """
    Generates a human LPO number like: 'LPO-2025-000123'.
    Prefix can be overridden via SACSOL_LPO_PREFIX env/setting.
    """
    prefix = getattr(settings, "SACSOL_LPO_PREFIX", "LPO")
    year, n = _next_year_counter()
    return f"{prefix}-{year}-{n:06d}"


def next_supplier_code() -> str:
    """
    Generates a human supplier code like: 'SUP-2025-000124'.
    Shares the yearly counter with LPOs (simple, single-tenant design).
    If you want a dedicated supplier counter, define a SupplierSequence model later.
    """
    prefix = getattr(settings, "SACSOL_SUPPLIER_PREFIX", "SUP")
    year, n = _next_year_counter()
    return f"{prefix}-{year}-{n:06d}"


def public_verify_url(lpo: LPO) -> str:
    """
    Builds a public verify URL for the LPO. We try to use a base URL from settings.
    Fallback is a relative path that your frontend can handle.
    """
    base = getattr(settings, "SITE_URL", None) or getattr(settings, "FRONTEND_BASE_URL", "") or ""
    path = f"/verify/lpo/{lpo.lpo_number}"
    if base:
        return f"{base.rstrip('/')}{path}"
    return path

def scan_bytes_for_malware(data: bytes) -> bool:
      # return True if clean, False (or raise) if infected
    return True

def render_lpo_pdf_bytes(lpo: LPO) -> bytes:
    """
    Produces PDF bytes for the LPO.
    - If WeasyPrint is installed, render a simple HTML -> PDF.
    - Otherwise, return a minimal placeholder PDF (valid but empty).
    Replace the HTML/template with your branded layout + QR of public_verify_url(lpo).
    """
    # Try WeasyPrint if available
    try:
        from weasyprint import HTML
        verify = public_verify_url(lpo)
        html = f"""
        <html>
          <head>
            <meta charset="utf-8">
            <style>
              body {{ font-family: sans-serif; font-size: 12px; }}
              h1 {{ font-size: 18px; margin: 0 0 8px; }}
              table {{ border-collapse: collapse; width: 100%; }}
              th, td {{ border: 1px solid #ccc; padding: 6px; text-align: left; }}
              .meta td {{ border: none; padding: 2px 0; }}
            </style>
          </head>
          <body>
            <h1>{lpo.lpo_number}</h1>
            <table class="meta">
              <tr><td><b>Status:</b> {lpo.status}</td></tr>
              <tr><td><b>Supplier:</b> {lpo.supplier.name}</td></tr>
              <tr><td><b>Currency:</b> {lpo.currency}</td></tr>
              <tr><td><b>Delivery address:</b> {lpo.delivery_address or "-"}</td></tr>
              <tr><td><b>Expected delivery:</b> {lpo.expected_delivery_date or "-"}</td></tr>
              <tr><td><b>Payment terms:</b> {lpo.payment_terms or "-"}</td></tr>
              <tr><td><b>Verify:</b> {verify}</td></tr>
            </table>

            <h2>Items</h2>
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Description</th>
                  <th>Qty</th>
                  <th>Unit Price</th>
                  <th>Line Total</th>
                </tr>
              </thead>
              <tbody>
                {''.join(
                    f"<tr><td>{i+1}</td><td>{it.description or it.inventory_item}</td>"
                    f"<td>{it.qty}</td><td>{it.unit_price}</td><td>{it.line_total}</td></tr>"
                    for i, it in enumerate(lpo.items.all())
                )}
              </tbody>
            </table>

            <h2>Totals</h2>
            <table>
              <tbody>
                <tr><td>Subtotal</td><td>{lpo.subtotal}</td></tr>
                <tr><td>Tax</td><td>{lpo.tax_amount}</td></tr>
                <tr><td>Discount</td><td>{lpo.discount_amount}</td></tr>
                <tr><td><b>Grand Total</b></td><td><b>{lpo.grand_total}</b></td></tr>
              </tbody>
            </table>

            <p style="margin-top: 24px; font-size: 10px; color: #666;">
              Generated by Sacsol on {timezone.now().strftime("%Y-%m-%d %H:%M")} &middot; {verify}
            </p>
          </body>
        </html>
        """.strip()
        return HTML(string=html, base_url=getattr(settings, "SITE_URL", None)).write_pdf()
    except Exception:
        pass  # fall back to a tiny valid placeholder PDF

    # Minimal placeholder PDF bytes (valid PDF header with no content)
    return b"%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF\n"
