"""
Django settings for sacsol project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS','*').split(',')


COMPANY_NAME = os.getenv("COMPANY_NAME", "SACSOL ENGINEERING LIMITED")
COMPANY_ADDRESS = os.getenv("COMPANY_ADDRESS", "Plot 12, Industrial Layout|Lagos, Nigeria").split("|")
COMPANY_PHONE = os.getenv("COMPANY_PHONE", "+234 800 000 0000")
COMPANY_EMAIL = os.getenv("COMPANY_EMAIL", "info@sacsol.com")
COMPANY_RC_NUMBER = os.getenv("COMPANY_RC_NUMBER", "RC 1234567")
COMPANY_TAX_ID = os.getenv("COMPANY_TAX_ID", "TIN 0123456789")
COMPANY_LOGO_PATH = Path(
    os.getenv("COMPANY_LOGO_PATH", BASE_DIR / "core" / "static" / "sacsol.png")
)
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:3000")
SACSOL_LPO_PREFIX = os.getenv("SACSOL_LPO_PREFIX", "LPO")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles',
    'rest_framework','rest_framework_simplejwt','drf_spectacular','corsheaders',
    'inventory','accounts.apps.AccountsConfig','procurement'
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.BlockInventoryWritesForNonSuperuser',  # admin-only guard
]

# --- CORS/CSRF ---
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "true").lower() == "true"
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS","").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS","").split(",") if o.strip()]

ROOT_URLCONF = 'sacsol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sacsol.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (  # ← add this
        'rest_framework.permissions.IsAuthenticated',
    ),
    "EXCEPTION_HANDLER": "core.exceptions.exception_handler",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 25,
}

REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
    "rest_framework.throttling.UserRateThrottle",
]
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "user": os.getenv("DRF_THROTTLE_USER", "2000/day"),
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Sacsol API",
    "DESCRIPTION": "Inventory management API for Sacsol",
    "VERSION": "1.0.0",
    "SERVERS": [{"url": "/"}],
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": True,
    "SCHEMA_PATH_PREFIX": r"/api",  # if you mount under /api
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# after load_dotenv() and BASE_DIR defined
POSTGRES_HOST = os.getenv('POSTGRES_HOST') or os.getenv('DB_HOST') or ''
POSTGRES_NAME = os.getenv('POSTGRES_DB') or os.getenv('DB_NAME') or 'inventory'
POSTGRES_USER = os.getenv('POSTGRES_USER') or os.getenv('DB_USER') or 'postgres'
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD') or os.getenv('DB_PASSWORD') or 'postgres'
POSTGRES_PORT = os.getenv('POSTGRES_PORT') or os.getenv('DB_PORT') or '5432'

if POSTGRES_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': POSTGRES_NAME,
            'USER': POSTGRES_USER,
            'PASSWORD': POSTGRES_PASSWORD,
            'HOST': POSTGRES_HOST,
            'PORT': POSTGRES_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIMEZONE", "Africa/Lagos")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media (only if you use file uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Procurement knobs ---

MAX_PDF_UPLOAD_MB = int(os.getenv("MAX_PDF_UPLOAD_MB", "5"))
IMAGE_MAX_DIM = int(os.getenv("IMAGE_MAX_DIM", "2000"))
SACSOL_LPO_PREFIX = os.getenv("SACSOL_LPO_PREFIX", "LPO")
SACSOL_SUPPLIER_PREFIX = os.getenv("SACSOL_SUPPLIER_PREFIX", "SUP")
SITE_URL = os.getenv("SITE_URL")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL")
MAX_IMAGE_UPLOAD_KB = int(os.getenv("MAX_IMAGE_UPLOAD_KB", "300"))
ALLOWED_ATTACHMENT_CONTENT_TYPES = os.getenv(
    "ALLOWED_ATTACHMENT_CONTENT_TYPES",
    "image/jpeg,image/png,image/webp,application/pdf"
).split(",")


