# Generated by Django 5.2.7 on 2025-10-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryattachment'),
        ('procurement', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpoitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryentry'),
        ),
    ]
